#!/usr/bin/env python
# coding: utf-8

# In[117]:


import json 
import pandas as pd 
from pandasql import sqldf

with open('data/US_category_id.json') as f:
    cat_data = json.load(f)
    ID = [int(x.get('id')) for x in cat_data.get('items')]
    category = [x.get('snippet').get('title')for x in cat_data.get('items')]
    category_id_dict = dict(zip(ID, category))
    #print(category_id_dict)
    
vid_data_df = pd.read_csv('data/USvideos.csv')

vid_data_df = vid_data_df.drop(['video_id', 'tags','thumbnail_link', 'description' ],axis=1)
vid_data_df['category_name'] = vid_data_df['category_id'].map(category_id_dict)
#print(vid_data_df)

print(sqldf("SELECT COUNT(*), category_name FROM vid_data_df group by category_id;", locals()))


# In[ ]:




